#!/usr/bin/env python3
"""
gen_data.py — Embeds all CSV files into js/data-embedded.js
Run once: python gen_data.py
After that, open index.html directly in any browser (no server needed).
"""
import csv
import json
import os

BASE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE, 'npcil_sm11_demo_input_data')
OUTPUT = os.path.join(BASE, 'js', 'data-embedded.js')

FILES = {
    'jobs':        'jobs.csv',
    'wps':         'wps_extracted_parameters.csv',
    'qualMapping': 'qualification_mapping.csv',
    'qualMatrix':  'qualification_matrix.csv',
    'welders':     'welders.csv',
    'consumables': 'consumables_reference.csv',
    'pqr':         'pqr_reference.csv',
    'inspection':  'inspection_requirements.csv',
}

def read_csv(filename):
    path = os.path.join(DATA_DIR, filename)
    rows = []
    with open(path, encoding='utf-8', newline='') as f:
        for row in csv.DictReader(f):
            rows.append({k.strip(): v.strip() for k, v in row.items()})
    return rows

def safe_float(v, default=0.0):
    try: return float(v)
    except: return default

def safe_int(v, default=0):
    try: return int(v)
    except: return default

def main():
    data = {}
    for key, fname in FILES.items():
        data[key] = read_csv(fname)
        print(f"  {fname}: {len(data[key])} rows")

    # Numeric coercions
    for j in data['jobs']:
        j['thickness_mm'] = safe_float(j.get('thickness_mm'))

    for w in data['wps']:
        w['groove_thickness_min_mm'] = safe_float(w.get('groove_thickness_min_mm'))
        w['groove_thickness_max_mm'] = safe_float(w.get('groove_thickness_max_mm'))
        w['pwht_required']            = w.get('pwht_required', 'False') == 'True'
        w['extraction_review_required'] = w.get('extraction_review_required', 'False') == 'True'
        w['extraction_confidence']    = safe_float(w.get('extraction_confidence'))

    for q in data['qualMatrix']:
        q['min_thickness_mm']             = safe_float(q.get('min_thickness_mm'))
        q['max_thickness_mm']             = safe_float(q.get('max_thickness_mm', '999'))
        q['pwht_capable']                 = q.get('pwht_capable', 'False') == 'True'
        q['requires_special_endorsement'] = q.get('requires_special_endorsement', 'False') == 'True'

    for w in data['welders']:
        w['days_until_expiry'] = safe_int(w.get('days_until_expiry'))
        w['recent_ncr_count']  = safe_int(w.get('recent_ncr_count'))

    js = (
        "// Auto-generated by gen_data.py — do not edit manually.\n"
        "// Re-run: python gen_data.py\n"
        "// All CSV data is embedded here so index.html works without a server.\n\n"
        f"const EMBEDDED_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    )

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(js)

    total = sum(len(v) for v in data.values())
    print(f"\nOK Generated {OUTPUT}  ({total} total records, {os.path.getsize(OUTPUT)//1024} KB)")
    print("  Open index.html directly in your browser -- no server needed.")

if __name__ == '__main__':
    print("Embedding CSV data into JavaScript...\n")
    main()
